In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from glob import glob
import plotly.graph_objects as go
from scipy.signal import butter
from tqdm import tqdm
from sklearn.preprocessing import MinMaxScaler

In [2]:
def FAT(series, threshold=0.02):
    
    '''
    Returns the FAT (First Arrival Time) of a given soniclog reading
    
    Input: 
    --------------
    1. Takes a pandas series as input,
    2. limit is the threshold ratio for excluding the low amplitudes
    
    returns the time and amplitude for the first three peaks
    '''
    if type(series) == pd.Series:
        # 1. Convert series
        df = pd.DataFrame({"value": series,                      
                   "bdiff": series.diff(1),
                   "fdiff": series.diff(-1)
                  })

        df = df.reset_index()
        df.rename(columns={"index":"Time"}, inplace=True)
        df["Time"] = df["Time"].astype(int)
        df = df.sort_values(by="Time")
        df["peak"] = ((df["bdiff"]>0) & (df["fdiff"]>=0)) | ((df["bdiff"]<=0) & (df["fdiff"]<0))
        df["abs"] = np.abs(df["value"])

        scaler = MinMaxScaler()
        df["norm_values"] = scaler.fit_transform(df["abs"].values.reshape(-1,1))

        df_peaks = df[df["peak"]].copy()
        df_peaks["bdiff1"] = df_peaks["abs"].diff(1)
        df_peaks["fdiff1"] = df_peaks["abs"].diff(-1)

        df_results = df_peaks[(df_peaks["bdiff1"]>0) & (df_peaks["fdiff1"]<=0)].copy()
        df_results = df_results[["Time","value","abs","norm_values"]]

        df_results["bslope"] = df_results["abs"].diff(1)/df_results["Time"].diff(1)
        
        df_final = df_results[(df_results["bslope"]>0) & (df_results["norm_values"]>threshold)].sort_values(by="Time")
           
        ## return the first three peaks:
        first_peak = df_final[["Time","value"]].iloc[0,:].values
        if first_peak[1] < 0:
            index = np.where(df_peaks["Time"].values==first_peak[0])[0][0]
            first_peak = df_peaks[["Time","value"]].values[index-1]

        next_peaks = df_peaks[(df_peaks["Time"]>first_peak[0])][["Time","value"]].iloc[0:2,:].values.ravel()
        all_peaks = np.hstack((first_peak,next_peaks))
        return all_peaks
    
    else:
        print("Values must be pandas series object")
        return None

In [4]:
%%time

folder = "C:\\Users\\kvba\\OneDrive - Ramboll\\Projects\\Geotechnical and geophysics\\Interpretation of sonic logging reading\\data\\Raw data\\"

columns = ["Depth", "ArrivalTime1(µs)", "Amplitude1(float)", "ArrivalTime2(µs)", "Amplitude2(float)", "ArrivalTime3(µs)", "Amplitude3(float)"]

filenames = ["600mm","800mm","1000mm"]
threshold = 0.02

for file in filenames:
    
    print("Analysing %s..."%file)
    dfx = pd.read_csv(folder+file+".csv")
    
    all_data = []
    
    for row in tqdm(range(dfx.shape[0])):
        
        values = dfx.iloc[row,1:]
        final_values = [dfx.iloc[row,0]]
        fat_values = FAT(values, threshold=threshold)
        final_values.extend(list(fat_values))
        all_data.append(final_values)
        
    df_out = pd.DataFrame(all_data, columns=columns)
    df_out.to_excel(file+".xlsx")

  0%|                                                                                         | 0/1750 [00:00<?, ?it/s]

Analysing 600mm...

100%|██████████████████████████████████████████████████████████████████████████████| 1750/1750 [00:21<00:00, 81.58it/s]
  0%|                                                                                         | 0/1749 [00:00<?, ?it/s]

Analysing 800mm...

100%|██████████████████████████████████████████████████████████████████████████████| 1749/1749 [00:23<00:00, 75.45it/s]
  0%|                                                                                         | 0/1749 [00:00<?, ?it/s]

Analysing 1000mm...

100%|██████████████████████████████████████████████████████████████████████████████| 1749/1749 [00:22<00:00, 79.22it/s]

Wall time: 1min 7s

In [5]:
df_out

,Depth,ArrivalTime1(µs),Amplitude1(float),ArrivalTime2(µs),Amplitude2(float),ArrivalTime3(µs),Amplitude3(float)
0,3.72,300.0,65.0,320.0,-1111.0,340.0,2571.0
1,3.74,304.0,440.0,320.0,-1217.0,340.0,2418.0
2,3.76,304.0,485.0,324.0,-1218.0,340.0,2581.0
3,3.78,308.0,565.0,320.0,-746.0,340.0,1882.0
4,3.80,304.0,482.0,324.0,-1335.0,344.0,2637.0
...,...,...,...,...,...,...,...
1744,38.60,400.0,537.0,420.0,-3276.0,444.0,9255.0
1745,38.62,400.0,563.0,420.0,-3023.0,444.0,8329.0
1746,38.64,404.0,529.0,424.0,-3542.0,452.0,12749.0
1747,38.66,408.0,619.0,428.0,-4669.0,456.0,15865.0
1748,38.68,408.0,998.0,432.0,-6324.0,456.0,18967.0